manifest:
  remotes:
    - name: zmk-tom60
      url-base: https://github.com/tabbeber/zmk-tom60
  projects:
    - name: zmk
      remote: zmk-tom60
      revision: main
      import: app/west.yml
  self:
    path: config
