manifest:
  remotes:
    - name: tabbeber
      url-base: https://github.com/tabbeber
  projects:
    - name: zmk-tom60
      remote: tabbeber
      revision: main
      import: app/west.yml
  self:
    path: config
